# Generated by Django 5.2 on 2025-04-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_bilhete_identidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('rh', 'RH'), ('colaborador', 'Colaborador'), ('canditato', 'Canditato')], max_length=20),
        ),
    ]
