# Generated by Django 5.2 on 2025-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('rh', 'RH'), ('colaborador', 'Colaborador'), ('canditato', 'Candidato')], max_length=20),
        ),
    ]
