# Generated by Django 5.2 on 2025-04-10 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_question_points_test_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
